spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/to2
    username: to2
    password: to2
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  file:
    name: logs/app.log
    path: logs

site:
  protocol-and-host: #
    
recaptcha:
  siteKey: #
  privateKey: #
  active: false

google-analytics:
  active: false
  measurement-id: #
